#!/usr/bin/env bash
# Reject commits whose message credits an AI agent as an author or a generator.
#
# GeoGuard Ledger's contributors are the humans who wrote the code. A
# `Co-Authored-By:` trailer is all it takes for GitHub to count the named
# account as a project contributor, so an agent name in a trailer quietly shows
# up as an extra avatar in the sidebar and the Insights graph. That happened
# once (a `Generated with Codebuff 🤖 / Co-Authored-By: Codebuff` footer) and
# had to be amended out of main; this check is what stops it landing again.
#
# Only commit messages are read — file contents are never inspected.
#
# Usage:
#   scripts/check_no_ai_attribution.sh                 # every reachable commit
#   scripts/check_no_ai_attribution.sh origin/main..HEAD
#
# Exits 1 and prints the offending lines when attribution is found.

set -euo pipefail

if [ -n "${1:-}" ]; then
  revisions=("$1")
else
  revisions=(--all)
fi

# One `git log` for the whole range, with the body separated from the hash and
# the records separated from each other, so awk can join the report without
# forking a process per commit.
git log "${revisions[@]}" --format='%H%x1f%B%x1e' | awk '
BEGIN {
  RS = "\x1e"
  FS = "\x1f"

  # Agent names we never want credited. Matched case-insensitively against any
  # line that reads as authorship or generation credit, so both
  # "Co-Authored-By: Codebuff <noreply@codebuff.com>" and
  # "Generated with Codebuff" trip it, as does a vendor email alone.
  agents = "codebuff|claude|anthropic|openai|chatgpt|copilot|cursor|devin|aider|gemini|codex|windsurf|swe-agent|opencode|tabnine|qodo|zencoder"

  # "credit" lines: authorship/generation trailers. The leading `[^[:alpha:]]*`
  # steps over the "🤖 " prefix these footers conventionally carry.
  credit = "^[^[:alpha:]]*(co-authored-by|co-authored|generated with|generated by|generated-by|assisted by|assisted-by|created with|created-by|built with|written by|authored by)"

  commits = 0
  offenders = 0
  total = 0
}

NF >= 2 {
  hash = $1
  gsub(/[[:space:]]+/, "", hash)
  commits++

  bad = ""
  lines = split($2, body, "\n")
  for (i = 1; i <= lines; i++) {
    line = body[i]
    low = tolower(line)
    reason = ""

    if (low ~ credit && low ~ agents)
      reason = "credits an AI agent"
    else if (index(line, "\360\237\244\226") > 0)  # U+1F916 🤖
      reason = "carries the AI generation marker"

    if (reason != "") {
      total++
      bad = bad "    " line "   (" reason ")\n"
    }
  }

  if (bad != "") {
    offenders++
    printf "\n%s\n%s", hash, bad
  }
}

END {
  if (offenders > 0) {
    printf "\n❌ AI attribution in %d of %d commit message(s), %d line(s) total.\n", offenders, commits, total
    printf "\nStrip the trailer and rewrite the commit(s):\n"
    printf "    git commit --amend                # the most recent commit\n"
    printf "    git rebase -i HEAD~N              # older commits\n"
    printf "    git push --force-with-lease\n"
    printf "\nSee \"Commit Conventions\" in CONTRIBUTING.md for why: a Co-Authored-By\n"
    printf "trailer makes GitHub count that account as a project contributor.\n"
    exit 1
  }
  printf "✅ No AI attribution in %d commit message(s).\n", commits
}
'
